---
title: "Solução Lista 01"
author: |
        | Nome: Bruna Alves Mazier
        | E-mail: bruna.maziero@aluno.ufabc.edu.br
        | Nome: Pedro Cardoso Alves Barbuti
        | E-mail: pedro.barbuti@aluno.ufabc.edu.br
        | (Não é preciso informar os RAs)
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,
                      fig.align='center',
                      cache=TRUE,
                      out.width = "60%",
                      out.heigth = "60%",
                      warning=FALSE,
                      message=FALSE)
options(width =70)
```

## Exercício 01
```{r}
A <- matrix(c(12, -1, -5, 0,
             -1, 7, 2, -1,
             -5, 2, 10, 1,
             0, -1, 1, 3), nrow = 4, byrow = TRUE)

b <- c(1, 2, 3, 4)
x <- solve(A, b)
print(x)

```


## Exercício 02
```{r}
its_positive <- function(A) {
  n <- nrow(A)
  for (i in 1:n) {
    submatriz <- A[1:i, 1:i] 
    if (det(submatriz) <= 0) {
      return(FALSE)  
    }
  }
  
  return(TRUE)  
  
  # Testing with matrix A from exercise 1
A <- matrix(c(12, -1, -5, 0,
              -1, 7, 2, -1,
              -5, 2, 10, 1,
              0, -1, 1, 3), 
            nrow = 4, byrow = TRUE)

its_positive(A)
}
```

## Exercício 03
```{r}
library(ggplot2)

dados <- data.frame(
  Angulo = seq(-2 * pi, 2 * pi, length.out = 200),
  Seno = sin(seq(-2 * pi, 2 * pi, length.out = 200)),
  Cosseno = cos(seq(-2 * pi, 2 * pi, length.out = 200))
)

ggplot(dados, aes(x = Angulo)) +
  geom_line(aes(y = Seno, color = "Seno"), linewidth = 1.2) +
  geom_line(aes(y = Cosseno, color = "Cosseno"), linewidth = 1.2) +
  scale_color_manual(values = c("Seno" = "blue", "Cosseno" = "red")) +
  labs(title = "Funções Seno e Cosseno", x = "Ângulo (radianos)", y = "Valor", color = "Função") +
  theme_bw() +
  scale_x_continuous(breaks = seq(-2*pi, 2*pi, pi), labels = c("-2π", "-π", "0", "π", "2π"))
```

## Exercício 04
```{r}
library(ggplot2)

set.seed(1)
X <- matrix(runif(100, -1, 1), nrow = 10)
A <- t(X) %*% X

lambdas <- seq(0, 5, length.out = 100)
cond_numbers <- numeric(length(lambdas))

for (i in seq_along(lambdas)) {
  A_mod <- A + lambdas[i] * diag(10)
  cond_numbers[i] <- kappa(A_mod)
}

dados <- data.frame(Lambda = lambdas, CondNumber = cond_numbers)

ggplot(dados, aes(x = Lambda, y = CondNumber)) +
  geom_line() +
  labs(title = "Número de Condicionamento vs. Lambda", x = "Lambda", y = "Número de Condicionamento") +
  theme_bw() +
  scale_y_log10()
```




